console.log('Abra o arquivo scripts.js.')
console.log('Multiplicação *')
console.log(4 * 4)
console.log('Divisão /')
console.log(50 / 4)
console.log('Soma +')
console.log(25 + 32)
console.log('Subtração -')
console.log(7 - 2)
console.log('Resto da Divisão %')
console.log(5 % 2)
console.log('Incremento ++')
let number = 10
console.log(number++ + ' incrementar após')
console.log('number: ' + number)
console.log(++number + ' incrementar antes')
console.log('Decremento --')
console.log(number-- + ' Decrementar após')
console.log('number: ' + number)
console.log(--number + ' Decrementar antes')
console.log('Exponencial **')
console.log(5 ** 2)